version: '3.7'

services:
  voter:
    image: voter_frontend:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_ACCESS_PROVIDER_IP=${REACT_APP_ACCESS_PROVIDER_IP}
      - REACT_APP_ACCESS_PROVIDER_PORT=${REACT_APP_ACCESS_PROVIDER_PORT}
      - REACT_APP_IDENTITY_PROVIDER_IP=${REACT_APP_IDENTITY_PROVIDER_IP}
      - REACT_APP_IDENTITY_PROVIDER_PORT=${REACT_APP_IDENTITY_PROVIDER_PORT}
      - REACT_APP_ETHSTATS_IP=${REACT_APP_ETHSTATS_IP}
      - REACT_APP_ETHSTATS_PORT=${REACT_APP_ETHSTATS_PORT}
    labels:
      - "traefik.docker.network=e-voting"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${VOTER_FRONTEND_EXTERNAL}"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
    networks:
      - e-voting

networks:
  e-voting:
    external: true
