version: '3.7'

services:
  voter:
    image: voter_frontend:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_ACCESS_PROVIDER_IP=${REACT_APP_ACCESS_PROVIDER_IP}
      - REACT_APP_ACCESS_PROVIDER_PORT=${REACT_APP_ACCESS_PROVIDER_PORT}
      - REACT_APP_IDENTITY_PROVIDER_IP=${REACT_APP_IDENTITY_PROVIDER_IP}
      - REACT_APP_IDENTITY_PROVIDER_PORT=${REACT_APP_IDENTITY_PROVIDER_PORT}
    ports:
      - 3000:80
    networks:
      - e-voting

networks:
  e-voting:
    external: true
