version: "3.7"

services:
  sealer:
    image: voting_sealer_${SEALER_NR}:latest
    container_name: sealer_${SEALER_NR}
    environment:
      - VOTING_AUTH_BACKEND_PORT=${VOTING_AUTH_BACKEND_PORT}
      - VOTING_AUTH_BACKEND_IP=${VOTING_AUTH_BACKEND_IP}
      - SEALER_BACKEND_PORT=${SEALER_BACKEND_PORT}
      - SEALER_BACKEND_IP=${SEALER_BACKEND_IP}
      - SEALER_FRONTEND_PORT=${SEALER_FRONTEND_PORT}
      - SEALER_FRONTEND_IP=${SEALER_FRONTEND_IP}
      - PARITY_NODE_PORT=${PARITY_NODE_PORT}
      - PARITY_NODE_IP=${PARITY_NODE_IP}
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_SEALER_FRONTEND_PORT=${SEALER_FRONTEND_PORT}
      - REACT_APP_SEALER_FRONTEND_IP=${SEALER_FRONTEND_IP}
      - REACT_APP_SEALER_BACKEND_PORT=${SEALER_BACKEND_PORT}
      - REACT_APP_SEALER_BACKEND_IP=${SEALER_BACKEND_IP}
      - REACT_APP_VOTING_AUTH_BACKEND_PORT=${VOTING_AUTH_BACKEND_PORT}
      - REACT_APP_VOTING_AUTH_BACKEND_IP=${VOTING_AUTH_BACKEND_IP}
      - PORT=${SEALER_FRONTEND_PORT}
    ports:
      - ${SEALER_BACKEND_PORT}:${SEALER_BACKEND_PORT}
    networks:
      - e-voting
    command: node ./backend/dist/server.js

networks:
  e-voting:
    external: true
