version: '3.7'

services:
  identity_provider:
    image: identity_provider:latest
    environment:
      - IDENTITY_PROVIDER_BACKEND_PORT=${IDENTITY_PROVIDER_BACKEND_PORT}
      - IDENTITY_PROVIDER_BACKEND_IP=${IDENTITY_PROVIDER_BACKEND_IP}
      - ACCESS_PROVIDER_BACKEND_PORT=${ACCESS_PROVIDER_BACKEND_PORT}
      - ACCESS_PROVIDER_BACKEND_IP=${ACCESS_PROVIDER_BACKEND_IP}
      - NODE_ENV=${NODE_ENV}
      - VOTER_FRONTEND=${VOTER_FRONTEND}
    labels:
      - "traefik.docker.network=e-voting"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${IDENTITY_PROVIDER_BACKEND_EXTERNAL}"
      - "traefik.basic.port=${IDENTITY_PROVIDER_BACKEND_PORT}"
      - "traefik.basic.protocol=http"
    networks:
      - e-voting
    command: node dist/server.js

networks:
  e-voting:
    external: true
