version: '3.7'

services:
  access_provider:
    image: access_provider:latest
    environment:
      - ACCESS_PROVIDER_BACKEND_PORT=${ACCESS_PROVIDER_BACKEND_PORT}
      - ACCESS_PROVIDER_BACKEND_IP=${ACCESS_PROVIDER_BACKEND_IP}
      - VOTING_AUTH_BACKEND_PORT=${VOTING_AUTH_BACKEND_PORT}
      - VOTING_AUTH_BACKEND_IP=${VOTING_AUTH_BACKEND_IP}
      - PARITY_NODE_PORT=${PARITY_NODE_PORT}
      - PARITY_NODE_IP=${PARITY_NODE_IP}
      - PARITY_NODE_EXTERNAL_IP=${PARITY_NODE_EXTERNAL_IP}
      - PARITY_NODE_EXTERNAL_PORT=${PARITY_NODE_EXTERNAL_PORT}
      - NODE_ENV=${NODE_ENV}
    labels:
      - "traefik.docker.network=e-voting"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${ACCESS_PROVIDER_BACKEND_EXTERNAL}"
      - "traefik.basic.port=${ACCESS_PROVIDER_BACKEND_PORT}"
      - "traefik.basic.protocol=http"
    networks:
      - e-voting
    command: node dist/server.js

networks:
  e-voting:
    external: true
