version: "3.7"

services:
  sealer_authority:
    container_name: sealer_authority_${SEALER_NR}
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        NETWORK_NAME: ${NETWORK_NAME}
        ID: ${ID}
    command: >
      --jsonrpc-cors all
      --port ${PORT}
      --jsonrpc-port ${RPC_PORT}
      --ws-port ${WS_PORT}
      --jsonrpc-interface all
      --engine-signer ${SIGNER_ADDRESS}
      --config /parity/config/authority.toml
    ports:
      - ${RPC_PORT}:${RPC_PORT}
    networks:
      - e-voting

networks:
  e-voting:
    external: true
